### PR TITLE
When addAppearListener is added, hover view cannot be dismissed. FIXED

### PR DESCRIPTION
**Pull request by milosjovac**
If statement has one typo - lack of negation '!'. Negation added and mHoverStatus set a bit earlier.

### CODE REVIEW

**Comment by daimajia** [comment]
A really silly fault..  Thanks!

**Comment by milosjovac** [comment]
Yeah, no problem. Thank for the neat lib.

**Comment by milosjovac** [comment]
May I ask when will this change be available from the gradle dependency?

**Comment by daimajia** [comment]
I have released v1.0.4, check it.

**Comment by milosjovac** [comment]
Awesome! It works.

**Pull request merged**
